apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0mn8
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-0mn8@sha256:4e9386cee83ed8d026c8d7a643b81a08083edb7e408ed719075afd930b5a444d
        name: my-nodejs
        resources: {}
status: {}
